services:
  builder:
    container_name: "web-builder"
    build:
      context: .
      dockerfile: Dockerfile
    image: "web:local"
    entrypoint: [ "sh", "-c", "/app/builder" ]
    volumes:
      - "./:/app"
    networks:
      - vsite
    init: true # helps with signal forwarding and process reaping
    tty: true
    stdin_open: true
    healthcheck:
      test: [ "CMD-SHELL", "test -f /tmp/flag" ]
      interval: 5s
      timeout: 5s
      retries: 1000
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: web
    image: "web:local"
    hostname: web
    restart: always
    stop_signal: SIGINT
    entrypoint: [ "sh", "-c", "gunicorn vSite.wsgi --bind 127.0.0.1:8000" ]
    networks:
      - vsite
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - "../../:/app"
      - "/tmp:/tmp"
    depends_on:
      builder:
        condition: service_healthy

  db:
    container_name: vsite-db
    restart: always
    image: postgres:17.6-alpine3.22
    hostname: postgres
    networks:
      - vsite
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:

networks:
  vsite:
    name: vsite
    driver: bridge