name: Check
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Env
        run: cp tools/example.env .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Docker up
        run: docker-compose up