name: Check
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Env
        run: cp tools/example.env .env

      - name: Setup QEMU
        run: docker/setup-qemu-action@v3

      - name: Docker up
        run: docker-compose up